<%@ Page Language="C#" AutoEventWireup="true" CodeFile="AdminManageAppointment.aspx.cs" Inherits="AddModel" %>
<%@ Register TagName="HeaderTag" TagPrefix="HeaderPrefix" Src="~/Header.ascx" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Add New Model</title>
    <link href="~/Styles/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div class="page">
    <form id="form1" runat="server">
    <HeaderPrefix:HeaderTag ID="HeaderId" runat="server" />
    <h2 style="text-align:left">
        &nbsp;Manage Appointment
    </h2>
     <div style="width:100%;">
         <div style="text-align:center">
             <div style="margin:0 auto">
                 <asp:Label ID="lblMsg" runat="server" ForeColor="Red" Font-Bold="true" EnableViewState="false" />
             </div>
         </div>
        
        <br /><br />
        <table style="width:100%">
            <tr>
                <td>
                    <div class="rounded_corners" style="width:95%;margin:0 auto" id="divGridView" runat="server">
                        <asp:GridView ID="gridView" CssClass="rounded_corners" runat="server" AutoGenerateColumns="false" Width="100%" HeaderStyle-BackColor="#3AC0F2"
                            HeaderStyle-ForeColor="White" RowStyle-BackColor="white" AlternatingRowStyle-BackColor="White"
                            RowStyle-ForeColor="#3A3A3A" 
                            DataSourceID="sqlDataSource" DataKeyNames="AppointmentId"
                            AutoGenerateEditButton="true"
                            AutoGenerateDeleteButton="true" HorizontalAlign="Center">
                            <Columns>
                               <asp:TemplateField HeaderText="Brand">
                                    <ItemTemplate>
                                        <asp:Label ID="lblBrand" Text='<%#Eval("BrandName") %>' runat="server" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Model">
                                    <ItemTemplate>
                                        <asp:Label ID="lblModel" Text='<%#Eval("ModelName") %>' runat="server" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                 <asp:TemplateField HeaderText="Color">
                                    <ItemTemplate>
                                        <asp:Label ID="lblColor" Text='<%#Eval("CarColor") %>' runat="server" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="CustomerName">
                                    <ItemTemplate>
                                        <asp:Label ID="lblCustomer" Text='<%#Eval("FirstName") %>' runat="server" />
                                         <asp:Label ID="lblCustomer1" Text='<%#Eval("LastName") %>' runat="server" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="CustomerId">
                                    <ItemTemplate>
                                        <asp:Label ID="lblCust" Text='<%#Eval("CustId") %>' runat="server" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                 <asp:TemplateField HeaderText="Engine">
                                    <ItemTemplate>
                                        <asp:Label ID="lblEngine" Text='<%#Eval("CarEngineType") %>' runat="server" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Apoointment Date/Time">
                                    <ItemTemplate>
                                        <asp:Label ID="lblDateTime" Text='<%#Eval("PreferredDateTime") %>' runat="server" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                 <asp:TemplateField HeaderText="Engine">
                                    <EditItemTemplate>
                                        <asp:DropDownList ID="DropDownList1" runat="server" SelectedValue='<%# Bind("Status") %>'>
                                            <asp:ListItem Text="Canceled [No Stock]" Value="Canceled [No Stock]"></asp:ListItem>
                                            <asp:ListItem Text="Canceled [Duplicate Appointment]" Value="Canceled [Duplicate Appointment]"></asp:ListItem>
                                            <asp:ListItem Text="Scheduled" Value="Scheduled"></asp:ListItem>
                                            <asp:ListItem Text="Waiting for Approval" Value="Waiting for Approval"></asp:ListItem>
                                        </asp:DropDownList>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Status") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                        </asp:GridView>
                    </div>
                <asp:SqlDataSource ID="sqlDataSource" runat="server" />
                </td>
            </tr>
        </table>
    </div>
    </form>
    </div>
</body>
</html>
