<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Car.aspx.cs" Inherits="Car" %>
<%@ Register TagName="HeaderTag" TagPrefix="HeaderPrefix" Src="~/Header.ascx" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Car's information</title>
     <link href="~/Styles/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="page">
    <form id="form1" runat="server">
    <HeaderPrefix:HeaderTag ID="HeaderId" runat="server" />
    <div>
        <br />
        <br />
        <table class="tableClass" cellpadding="5" cellspacing="5">
            <tr>
                <td colspan="2"><asp:Label ID="msg" runat="server" ForeColor="Red" /></td>
            </tr>
             <tr>
                <td>Car Brand:</td>
                <td><asp:DropDownList ID="ddlBrandName" OnSelectedIndexChanged="onchange_ddlBrandName" AutoPostBack="True" runat="server"></asp:DropDownList></td>
            </tr>
            <tr>
                <td>Car Model:</td>
                <td><asp:DropDownList ID="ddlModelName" runat="server"></asp:DropDownList></td>
            </tr>
             <tr>
                <td>Car Color:</td>
                <td><asp:TextBox ID="txtCarColor" runat="server"></asp:TextBox></td>
            </tr>
             <tr>
                <td>Car Price:</td>
                <td><asp:TextBox ID="txtCarPrice" runat="server"></asp:TextBox></td>
            </tr>
             <tr>
                <td>Car Engine Type:</td>
                <td><asp:DropDownList ID="ddlEngineType" runat="server"></asp:DropDownList></td>
            </tr>
             <tr>
                <td>Car Mileage:</td>
                <td><asp:TextBox ID="txtMileage" runat="server"></asp:TextBox></td>
            </tr>
             <tr>
                <td>Car Image:</td>
                <td><asp:FileUpload id="fileUpload"  runat="server" /></td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td><asp:Button ID="btnSubmit" runat="server" Text="Submit" onclick="btnSubmit_Click" /></td>
            </tr>
            
        </table>
        <br /><br /><br />
        <table style="width:100%">
            <tr>
                <td>
                    <div class="rounded_corners" style="width:90%;margin:0 auto" id="divGridView" runat="server">
                        <asp:GridView ID="gridView" CssClass="rounded_corners" runat="server" AutoGenerateColumns="false" Width="100%" HeaderStyle-BackColor="#3AC0F2"
                            HeaderStyle-ForeColor="White" RowStyle-BackColor="white" AlternatingRowStyle-BackColor="White"
                            RowStyle-ForeColor="#3A3A3A" 
                            DataSourceID="sqlDataSource" DataKeyNames="CarId"
                            AutoGenerateEditButton="true"
                            AutoGenerateDeleteButton="true" HorizontalAlign="Center"
                            OnRowDataBound="gridview_RowDataBound">
                            <Columns>
                                <asp:TemplateField HeaderText="Brand" ItemStyle-Width="20%">
                                    <ItemTemplate>
                                        <asp:HyperLink ID="linkBrandName" Text='<%#Eval("BrandName") %>' runat="server" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Model" ItemStyle-Width="20%">
                                    <ItemTemplate>
                                        <asp:Label ID="lblModelName" Text='<%#Eval("ModelName") %>' runat="server" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:BoundField ItemStyle-Width="20%" ItemStyle-HorizontalAlign="Center" HeaderText="Color" DataField="CarColor" />
                                <asp:BoundField ItemStyle-Width="20%" ItemStyle-HorizontalAlign="Center" HeaderText="Price" DataField="CarPrice" />

                                <asp:TemplateField HeaderText="Mileage">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txtCarMileage"  Text='<%# Bind("CarMileage") %>'  runat="server" />
                                        <asp:RangeValidator ID="range1" ControlToValidate="txtCarMileage" runat="server" MinimumValue="1" MaximumValue="1000" Type="Integer" ErrorMessage="Enter proper value" ></asp:RangeValidator>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lblMileage" runat="server" Text='<%# Bind("CarMileage") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Engine">
                                    <EditItemTemplate>
                                        <asp:DropDownList ID="DropDownList1" runat="server" SelectedValue='<%# Bind("CarEngineType") %>'>
                                            <asp:ListItem Text="Petrol" Value="P"></asp:ListItem>
                                            <asp:ListItem Text="Disel" Value="D"></asp:ListItem>
                                        </asp:DropDownList>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("CarEngineType") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                        </asp:GridView>
                    </div>
                <asp:SqlDataSource ID="sqlDataSource" runat="server" />
                </td>
            </tr>
        </table>
    </div>
    </form>
    </div>
</body>
</html>
