<%@ Page Language="C#" AutoEventWireup="true" CodeFile="CustomerAppointmentDetails.aspx.cs" Inherits="AddModel" %>
<%@ Register TagName="HeaderTag" TagPrefix="HeaderPrefix" Src="~/Header.ascx" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Add New Model</title>
    <link href="~/Styles/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div class="page">
    <form id="form1" runat="server">
    <HeaderPrefix:HeaderTag ID="HeaderId" runat="server" />
    <h2 style="text-align:left">
        &nbsp;Appointment Details
    </h2>
     <div style="width:100%;">
         <div style="text-align:center">
             <div style="margin:0 auto">
                 <asp:Label ID="lblMsg" runat="server" ForeColor="Red" Font-Bold="true" EnableViewState="false" />
             </div>
         </div>
        
        <br /><br />
        <table style="width:100%">
            <tr>
                <td>
                    <div class="rounded_corners" style="width:80%;margin:0 auto" id="divGridView" runat="server">
                        <asp:GridView ID="gridView" CssClass="rounded_corners" runat="server" AutoGenerateColumns="false" Width="100%" HeaderStyle-BackColor="#3AC0F2"
                            HeaderStyle-ForeColor="White" RowStyle-BackColor="white" AlternatingRowStyle-BackColor="White"
                            RowStyle-ForeColor="#3A3A3A" 
                            DataSourceID="sqlDataSource" DataKeyNames="ModelId"
                            AutoGenerateEditButton="false"
                            AutoGenerateDeleteButton="false" HorizontalAlign="Center">
                            <Columns>
                                <asp:BoundField ItemStyle-Width="20%" ItemStyle-HorizontalAlign="Center" HeaderText="Brand" DataField="BrandName" />
                                <asp:BoundField ItemStyle-Width="20%" ItemStyle-HorizontalAlign="Center" HeaderText="Model" DataField="ModelName" />
                                <asp:BoundField ItemStyle-Width="20%" ItemStyle-HorizontalAlign="Center" HeaderText="Apoointment Date/Time" DataField="PreferredDateTime" />
                                <asp:BoundField ItemStyle-Width="20%" ItemStyle-HorizontalAlign="Center" HeaderText="Status" DataField="Status" />
                            </Columns>
                        </asp:GridView>
                    </div>
                <asp:SqlDataSource ID="sqlDataSource" runat="server" />
                </td>
            </tr>
        </table>
    </div>
    </form>
    </div>
</body>
</html>
